---
name: "rstcheck"

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      action: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install rstcheck
        run: |
          apt-get update && apt-get install rstcheck
      - name: Run rstcheck
        run: |
          rstcheck -r source/
