---
name: "rstcheck"

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: ghcr.io/staticrocket/psdk-doc-docker:latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run rstcheck
        run: |
          rstcheck -r source/
