---
name: "release"

on:
  push:
    branches: [master]
    tags: ["v*.*.*"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/staticrocket/psdk-doc-docker:latest
    permissions:
      actions: read
      contents: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build html release
        run: make html
      - name: Create html release zip
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'web.zip'
          directory: 'build/html'
      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/html/web.zip"
