---
name: "release"

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      action: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install python-sphinx
        run: |
          apt-get update && apt-get install python-sphinx
      - name: Build html release
        run: make
      - name: Create html release zip
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'web.zip'
          directory: 'build/html'
      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/html/web.zip"
          token: ${{ secrets.GHTOKEN }}
