---
name: "release"

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/staticrocket/psdk-doc-docker:latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      actions: read
      contents: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build html release
        run: make html
      - name: Create html release zip
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'web.zip'
          directory: 'build/html'
      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/html/web.zip"
      - name: Remove zip artifact
        run: rm build/html/web.zip
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
